language: java
jdk: openjdk11

install:
- echo "https://${GITHUB_TOKEN}:@github.com" > "$HOME/.git-credentials"
- unset GITHUB_TOKEN

- git config --global user.email gradleupdate@users.noreply.github.com
- git config --global user.name  gradleupdate
- git config --global credential.helper store
- git config --global core.autocrlf input
- git config --global push.default current

script:
- |
  if [ "$TRAVIS_BRANCH" ]; then
    rm -fr "$TRAVIS_BUILD_DIR"
    mkdir "$TRAVIS_BUILD_DIR"
    cd "$TRAVIS_BUILD_DIR"
    git clone --branch="$TRAVIS_BRANCH" --depth=1 "https://github.com/$TRAVIS_REPO_SLUG" .

    ./gradlew -v
    ./gradlew wrapper
    ./gradlew wrapper
    ./gradlew -v

    git add .
    if [ "$(git status --porcelain)" ]; then
      git commit -m "Bump to $(./gradlew -v | egrep ^Gradle)"
      git push origin
    fi
  fi
