sudo: false
language: java

install:
- echo "https://${GITHUB_TOKEN}:@github.com" > "$HOME/.git-credentials"
- unset GH_TOKEN

- git config --global user.email gradleupdate@users.noreply.github.com
- git config --global user.name  gradleupdate
- git config --global credential.helper store
- git config --global core.autocrlf input
- git config --global push.default current

- rm -fr "$TRAVIS_BUILD_DIR"
- mkdir "$TRAVIS_BUILD_DIR"
- cd "$TRAVIS_BUILD_DIR"
- git clone --branch="$TRAVIS_BRANCH" --depth=1 "https://github.com/$TRAVIS_REPO_SLUG" .

script:
- |
  ./gradlew -v
  ./gradlew wrapper
  ./gradlew wrapper
  ./gradlew -v
  ./gradlew -v | egrep ^Gradle > GRADLE_VERSION
  git add .
  if [ "$(git status --porcelain)" ]; then
    git commit -F GRADLE_VERSION
    git push origin
  fi
