sudo: false
language: java
jdk: oraclejdk7

install:
- git config --global user.email "$GH_USER_EMAIL"
- git config --global user.name  "$GH_USER_NAME"
- git config --global core.autocrlf "input"
- git config --global credential.helper "store --file=$HOME/.gitcredentials"
- echo "https://${GH_TOKEN}:@github.com" > $HOME/.gitcredentials
- git remote remove origin
- git remote add origin "https://github.com/${TRAVIS_REPO_SLUG}.git"

- curl -LO https://github.com/github/hub/releases/download/v2.2.0/hub-linux-amd64-2.2.0.tar.gz
- tar -C "$HOME" -zxf hub-linux-amd64-2.2.0.tar.gz
- export PATH="$PATH:$HOME/hub-linux-amd64-2.2.0"
- hub --version

script:
- ./.travis.sh

after_success:
- git push origin --delete "$TRAVIS_BRANCH"

branches:
  only:
    - /^update-gradle-template/
    - /^update-gradle-of/

env:
  global:
  - TERM=dumb
