language: java
jdk: openjdk11

install:
- mkdir -p $HOME/bin
- curl -L -o $HOME/bin/ghcp https://github.com/int128/ghcp/releases/download/v1.3.0/ghcp_linux_amd64
- chmod +x $HOME/bin/ghcp
- export PATH="$HOME/bin:$PATH"

script:
- ./gradlew -v
- ./gradlew wrapper
- ./gradlew wrapper
- ./gradlew -v

- |
  ghcp -u "${TRAVIS_REPO_SLUG%/*}" -r "${TRAVIS_REPO_SLUG#*/}" -b "$TRAVIS_BRANCH" \
    -m "Bump to $(./gradlew -v | egrep ^Gradle)" \
    gradle/ \
    gradlew \
    gradlew.bat \
    README.md
