sudo: false
language: java
jdk: oraclejdk7

install:
- ./gradlew -PgradleVersion="${TRAVIS_BRANCH##*-}" wrapper
script:
- ./gradlew -PgradleVersion="${TRAVIS_BRANCH##*-}" wrapper
- ./gradlew -PgradleVersion="${TRAVIS_BRANCH##*-}" wrapper

after_success:
- git config user.email "$GH_USER_EMAIL"
- git config user.name  "$GH_USER_NAME"
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git remote remove origin
- git remote add origin "https://github.com/${TRAVIS_REPO_SLUG}.git"
- git checkout -b "${TRAVIS_BRANCH##*-}"
- git add gradle/wrapper gradlew gradlew.bat
- git commit -m "Gradle ${TRAVIS_BRANCH##*-}"
- git push origin "${TRAVIS_BRANCH##*-}"

branches:
  only:
    - /^build-/

env:
  global:
  - TERM=dumb
